Repository Findock/findme-mobile-app, pull requests merged in 2022-02, with the labels that each got.

#1 FM-61 | Storybook init + story example + storybook app run profile
  .gitignore
  App.js
  app.config.js
  components/ExampleComponent.js
  package.json
  storybook/addons.js
  storybook/index.js
  storybook/rn-addons.js
  storybook/stories/.stories.js.example
  storybook/stories/CenterView/index.js
  storybook/stories/CenterView/style.js
  storybook/stories/ExampleComponent.stories.js
  storybook/stories/index.js
  yarn-error.log
  yarn.lock
Labels: boilerplate, feature, needs documentation, ready to merge

#2 Fm 75 create component input text
  .eslintrc.js
  .gitignore
  App.js
  babel.config.js
  components/ExampleComponent.js
  components/Inputs/FTextInput.jsx
  components/Utils/FKeyboardAvoidingView .jsx
  constants/locales.js
  package.json
  storybook/.stories.js.example
  storybook/index.js
  storybook/stories/CenterView/index.js
  storybook/stories/CenterView/style.js
  storybook/stories/ExampleComponent.stories.js
  storybook/stories/Inputs/FTextInput.stories.js
  storybook/stories/index.js
  storybook/utils/CenterView.jsx
  themes/colors.js
  themes/icons.js
  themes/placements.js
  themes/sizes.js
  yarn-error.log
  yarn.lock
Labels: feature, ready to merge

#3 add new features for FInput component
  .eslintrc.js
  components/Inputs/FInput.jsx
  components/Inputs/FTextInput.jsx
  components/Utils/FKeyboardAvoidingView .jsx
  components/Utils/FKeyboardAvoidingView.jsx
  constants/inputTypes.js
  constants/locales.js
  storybook/stories/Inputs/FInput.stories.js
  storybook/stories/Inputs/FTextInput.stories.js
  storybook/stories/index.js
  themes/colors.js
  themes/icons.js
  themes/placements.js
  themes/sizes.js
Labels: feature, ready to merge

#4 FM-82 | Create heading component + heading stories
  .eslintrc.js
  babel.config.js
  components/Composition/FHeading.jsx
  components/Inputs/FInput.jsx
  jsconfig.json
  storybook/stories/Compositional/FHeading.stories.js
  storybook/stories/Inputs/FInput.stories.js
  storybook/stories/index.js
  themes/colors.js
  themes/fonts.js
  themes/placements.js
  themes/sizes.js
  yarn.lock
Labels: feature, ready to merge

#5 FM-67 | Eslint tests to CI + CI configuration
  .circleci/config.yml
  package.json
Labels: feature, ready to merge

#6 FM-83 | Create logo component + logo stories
  components/Composition/FLogo.jsx
  storybook/stories/Compositional/FLogo.stories.js
  storybook/stories/index.js
  themes/sizes.js
Labels: feature

#7 FM-79 | Create button component + button stories
  components/Buttons/FButton.jsx
  constants/buttonTypes.js
  package.json
  storybook/stories/Buttons/FButton.stories.js
  storybook/stories/index.js
  themes/sizes.js
  yarn.lock
Labels: feature

#8 FM-81 | Create image component + stories
  assets/login.png
  assets/registration.png
  components/Composition/FImage.jsx
  constants/images.js
  storybook/stories/Compositional/FImage.stories.js
  storybook/stories/index.js
Labels: feature

#12 FM-85 | Create registration screen
  App.js
  components/Buttons/FButton.jsx
  components/Composition/FHeading.jsx
  components/Composition/FImage.jsx
  components/Composition/FLogo.jsx
  components/Composition/FSpinner.jsx
  components/Forms/FRegistrationForm.jsx
  components/Inputs/FCheckbox.jsx
  components/Inputs/FInput.jsx
  components/Utils/FDismissKeyboard.jsx
  components/Utils/FKeyboardAvoidingView.jsx
  components/Utils/FKeyboardWrapper.jsx
  constants/errorMessages.js
  constants/locales.js
  layouts/FWelcome.layout.jsx
  package.json
  screens/Registration.screen.jsx
  yarn.lock
Labels: feature

#13 FM-95 | Create login form mock + navigation
  App.js
  babel.config.js
  components/Forms/FLoginForm.jsx
  components/Inputs/FInput.jsx
  constants/stackNavigatorNames.js
  jsconfig.json
  navigation/Navigation.jsx
  package.json
  yarn.lock
Labels: feature

#15 FM-98 | Save auth token in secure store on user's device
  app.config.js
  components/Forms/FLoginForm.jsx
  package.json
  services/authUser.service.js
  yarn.lock
Labels: feature

#16 FM-100 | Create auth token auto include mechanism
  .env.example
  .gitignore
  api/authClient.js
  app.config.js
  babel.config.js
  package.json
  yarn.lock
Labels: feature

#17 FM-108 | Auth redux reducer
  .eslintrc.js
  App.js
  babel.config.js
  components/Forms/FLoginForm.jsx
  jsconfig.json
  package.json
  store/auth/authSlice.js
  store/store.js
  yarn.lock
Labels: feature

#18 FM-94 | Handle login errors + fix registration's validation
  api/authClient.js
  api/noAuthClient.js
  components/Forms/FLoginForm.jsx
  components/Forms/FRegistrationForm.jsx
  constants/errorMessages.js
  constants/locales.js
  screens/Login.screen.jsx
  services/authUser.service.js
  services/createUser.service.js
Labels: feature, refactor

#20 FM-106 | Create temporary homepage + auth routes + refactor FSpinner component
  components/Composition/FSpinner.jsx
  components/Forms/FLoginForm.jsx
  components/Inputs/FInput.jsx
  constants/stackNavigatorNames.js
  layouts/FWelcome.layout.jsx
  navigation/Navigation.jsx
  screens/Homepage.screen.jsx
  screens/Login.screen.jsx
  themes/colors.js
Labels: feature, refactor

#22 FM-104 | Remove auth token on logout
  components/Forms/FLoginForm.jsx
  constants/locales.js
  navigation/Navigation.jsx
  screens/Homepage.screen.jsx
  store/auth/authSlice.js
Labels: feature

#25 FM-118 | Change terms accepted validation
  components/Forms/FRegistrationForm.jsx
Labels: feature

#26 FM-119 | Autocomplete login field + successful registration modal
  components/Forms/FLoginForm.jsx
  components/Forms/FRegistrationForm.jsx
  constants/locales.js
Labels: feature
