Repository Findock/findme-mobile-app, pull requests merged in 2022-05, with the labels that each got.

#69 FM-236 | Possibility to change announcement status
  components/Buttons/FButton.jsx
  components/Scoped/Announcement/Card/FAnnouncementCard.jsx
  components/Scoped/Announcement/Card/FAnnouncementCardActionsModal.jsx
  constants/components/modals/modalsMessages.js
  constants/locales.js
  enums/AnnouncementStatusEnum.js
  hooks/announcement/useChangeAnnouncementStatus.js
  hooks/announcement/useFavouriteAnnouncementManagement.js
  screens/AnnouncementPreview.screen.jsx
  screens/Homepage.screen.jsx
  services/announcement/archiveAnnouncement.service.js
  services/announcement/makeAnnouncementActive.service.js
  services/announcement/resolveAnnouncement.service.js
  themes/icons.js
Labels: feature

#70 FM-246 | Create my followed announcements screen
  components/Composition/FHeadingWithIcon.jsx
  components/Forms/Annoucement/FCreateAnnouncementForm.jsx
  components/Scoped/Announcement/Card/FAnnouncementCard.jsx
  components/Scoped/Announcement/FAnnouncementsList.jsx
  constants/locales.js
  constants/stackNavigatorNames.js
  navigation/Navigation.jsx
  screens/AnnouncementPreview.screen.jsx
  screens/Homepage.screen.jsx
  screens/MyAnnouncements.screen.jsx
  screens/MyFollowedAnnouncements.screen.jsx
  screens/UserAnnouncements.screen.jsx
  screens/UserProfile.screen.jsx
  screens/UserProfilePreview.screen.jsx
  services/announcement/getMyAnnouncements.service.js
  services/announcement/getUserAnnouncements.service.js
  services/announcement/searchAnnouncements.service.js
  themes/sizes.js
Labels: dont merge, feature, help wanted

#71 FM-249 | Create announcement filters drawer
  assets/infinity-b.png
  assets/infinity-w.png
  components/Buttons/FButton.jsx
  components/Buttons/FWideButton.jsx
  components/Composition/FAvatar.jsx
  components/Forms/Annoucement/FEditAnnouncementForm.jsx
  components/Inputs/Custom/FAnimalCoatColorSelectInput.jsx
  components/Inputs/Custom/FAnimalGenderTileSelectInput.jsx
  components/Inputs/Custom/FCategoryAnimalTileSelectInput.jsx
  components/Inputs/FBadgeSelectInput.jsx
  components/Inputs/FTileImageInput.jsx
  components/Inputs/Map/FMapView.jsx
  components/Scoped/Announcement/FAnnouncementsList.jsx
  components/Scoped/AnnouncementFiltersDrawer/FAnnouncementFiltersDrawer.jsx
  components/Scoped/LoginHistory/FLoginHistoryList.jsx
  components/Scoped/LoginHistory/FLoginHistoryListItem.jsx
  constants/filters-options/animalCategoriesIcons.js
  constants/filters-options/animalGenders.js
  constants/images.js
  constants/locales.js
  navigation/Navigation.jsx
  navigation/drawers/HomeDrawer.jsx
  screens/AnnouncementPreview.screen.jsx
  screens/Homepage.screen.jsx
  screens/LoginHistory.screen.jsx
  screens/UserProfile.screen.jsx
  screens/UserProfilePreview.screen.jsx
  store/announcement/announcementSlice.js
  store/filters-options/filtersOptionsSlice.js
  store/store.js
  themes/icons.js
  themes/opacities.js
  themes/sizes.js
Labels: feature, refactor

#72 FM-260 | Display announcement status
  components/Composition/FAvatar.jsx
  components/Composition/FImage.jsx
  components/Composition/Slider/FSlider.jsx
  components/Inputs/FTileImageInput.jsx
  components/Inputs/FTileSelectInput.jsx
  components/Scoped/Announcement/Card/FAnnouncementCard.jsx
  components/Scoped/Announcement/Card/FAnnouncementCardActionsModal.jsx
  components/Scoped/Announcement/FAnnouncementsList.jsx
  components/Scoped/AnnouncementFiltersDrawer/FAnnouncementFiltersDrawer.jsx
  constants/locales.js
  hooks/announcement/useChangeAnnouncementStatus.js
  layouts/FWelcome.layout.jsx
  screens/AnnouncementPreview.screen.jsx
  screens/ChangePassword.screen.jsx
  storybook/stories/Compositional/FImage.stories.js
  themes/colors.js
  themes/sizes.js
Labels: feature

#73 FM-250 | Create screen with all announcements with filters
  components/Inputs/Custom/FCategoryAnimalTileSelectInput.jsx
  components/Inputs/FBadgeSelectInput.jsx
  components/Inputs/FInput.jsx
  components/Inputs/Select/FSelectInput.jsx
  components/Inputs/Select/FSelectOption.jsx
  components/Inputs/Select/FSelectOptions.jsx
  components/Scoped/Announcement/Card/FAnnouncementCard.jsx
  components/Scoped/Announcement/FAnnouncementsList.jsx
  components/Scoped/AnnouncementFiltersDrawer/FAnnouncementFiltersDrawer.jsx
  components/Scoped/LoginHistory/FLoginHistoryListItem.jsx
  constants/components/inputs/placeholders.js
  constants/components/inputs/select-options/selectOptions.js
  constants/locales.js
  constants/stackNavigatorNames.js
  enums/AnnouncementSortingModeEnum.js
  hooks/announcement/useChangeAnnouncementStatus.js
  navigation/Navigation.jsx
  navigation/drawers/AllAnnouncementsDrawer.jsx
  navigation/styles/defaultHeaderOptions.js
  navigation/styles/headerWithoutShadowOptions.js
  navigation/utils/renderLogo.jsx
  screens/Homepage.screen.jsx
  screens/Select.screen.jsx
  screens/UserProfilePreview.screen.jsx
  screens/announcements/AddAnnouncement.screen.jsx
  screens/announcements/AllAnnouncements.screen.jsx
  screens/announcements/AnnouncementPreview.screen.jsx
  screens/announcements/EditAnnouncement.screen.jsx
  screens/announcements/MyAnnouncements.screen.jsx
  screens/announcements/MyFollowedAnnouncements.screen.jsx
  screens/announcements/UserAnnouncements.screen.jsx
  screens/user/ChangePassword.screen.jsx
  screens/user/ForgotPassword.screen.jsx
  screens/user/LoginHistory.screen.jsx
  screens/user/Settings.screen.jsx
  screens/user/UserProfile.screen.jsx
  store/filters-options/filtersOptionsSlice.js
  store/select/selectSlice.js
  themes/sizes.js
Labels: feature, refactor

#74 FM-275 | Add query and location filters in all announcements screen
  .eslintrc.js
  components/Forms/Annoucement/FCreateAnnouncementForm.jsx
  components/Forms/Annoucement/FEditAnnouncementForm.jsx
  components/Inputs/Select/FSelectInput.jsx
  components/Scoped/Announcement/FAnnouncementsList.jsx
  constants/filters-options/locationThresholds.js
  screens/Select.screen.jsx
  screens/announcements/AllAnnouncements.screen.jsx
  screens/announcements/AnnouncementPreview.screen.jsx
  store/select/selectSlice.js
Labels: feature
