Repository Findock/findme-mobile-app, pull requests merged in 2022-04, with the labels that each got.

#52 FM-169 | Modify location sharing permission
  components/Composition/FAvatar.jsx
  components/Composition/FModal.jsx
  components/Composition/FSpinner.jsx
  components/Forms/FLoginForm.jsx
  components/Scoped/LoginHistory/FLoginHistoryList.jsx
  components/Scoped/Settings/FSettingsFormScreen.jsx
  components/Scoped/Settings/FSettingsScreen.jsx
  constants/locales.js
  hooks/permissions/useCameraPermission.js
  hooks/permissions/useCameraRollPermission.js
  hooks/permissions/useLocationPermission.js
  hooks/useAppStateChange.js
  layouts/FDefault.layout.jsx
  package.json
  screens/ChangePassword.screen.jsx
  screens/Homepage.screen.jsx
  screens/UserProfile.screen.jsx
  screens/UserProfilePreview.screen.jsx
  services/uploadUserProfileImage.service.js
  yarn.lock
Labels: bugfix, feature

#53 FM-177 | Backend request to change password
  assets/change_password.png
  components/Composition/FModal.jsx
  constants/errorMessages.js
  constants/locales.js
  hooks/useErrorModal.js
  screens/ChangePassword.screen.jsx
  services/updatePassword.service.js
Labels: feature

#54 FM-214 | Create multi select component with showing selected options
  components/Forms/FRegistrationForm.jsx
  components/Inputs/FCheckbox.jsx
  components/Inputs/FInput.jsx
  components/Inputs/MultiSelect/FMultiSelect.jsx
  components/Inputs/MultiSelect/FMultiSelectOption.jsx
  constants/checkboxTypes.js
  constants/locales.js
  screens/Homepage.screen.jsx
  screens/LoginHistory.screen.jsx
  screens/Settings.screen.jsx
  screens/UserProfile.screen.jsx
  screens/UserProfilePreview.screen.jsx
  themes/icons.js
Labels: feature

#55 FM-218 | Create FTileImageInput + add possibility to close FModal on press outside
  assets/dog.png
  components/Composition/FImage.jsx
  components/Composition/FModal.jsx
  components/Inputs/FTileImageInput.jsx
  constants/buttonTypes.js
  constants/dateFormatTypes.js
  constants/images.js
  constants/locales.js
  constants/modalTypes.js
  constants/statusTypes.js
  constants/swipeButtonCellTypes.js
  hooks/permissions/useCameraPermission.js
  screens/Homepage.screen.jsx
  themes/icons.js
  themes/sizes.js
  utils/takePhotoWithCamera.js
Labels: feature

#58 FM-216 | Create map component
  assets/login.png
  assets/registration.png
  components/Inputs/Map/FMapView.jsx
  components/Inputs/Map/styles/styles.json
  constants/locales.js
  package.json
  screens/Homepage.screen.jsx
  themes/colors.js
  themes/sizes.js
  yarn.lock
Labels: feature

#57 FM-217 | Create select generic button
  assets/animalCategory/cat-b.png
  assets/animalCategory/cat-w.png
  components/Inputs/FTileSelectInput.jsx
  constants/images.js
  storybook/stories/Inputs/FTileSelectInput.stories.js
  storybook/stories/index.js
  themes/opacities.js
  themes/sizes.js
Labels: feature

#56 FM-215 | Create big text switch component
  components/Inputs/FBigSwitch.jsx
  storybook/stories/Inputs/FBigSwitch.stories.js
  storybook/stories/index.js
  themes/sizes.js
  yarn.lock
Labels: feature

#59 FM-213 | Create color component
  components/Inputs/FColorSelect.jsx
  storybook/stories/Inputs/FColorSelect.stories.js
  storybook/stories/index.js
  themes/sizes.js
Labels: feature

#62 FM-193 | Create images slider component
  components/Composition/Slider/FSlider.jsx
  components/Composition/Slider/FSliderDot.jsx
  themes/sizes.js
Labels: feature

#63 FM-196 | Create announcement preview screen
  App.js
  components/Composition/FAvatar.jsx
  components/Composition/FHeading.jsx
  components/Composition/FHeadingWithIcon.jsx
  components/Composition/FImage.jsx
  components/Composition/Slider/FSlider.jsx
  components/Composition/Slider/FSliderDot.jsx
  components/Forms/FRegistrationForm.jsx
  components/Inputs/Custom/FAnimalCoatColorSelectInput.jsx
  components/Inputs/FColorSelect.jsx
  components/Inputs/FInput.jsx
  components/Inputs/FTileSelectInput.jsx
  components/Inputs/Map/FMapView.jsx
  components/Scoped/LoginHistory/FLoginHistoryList.jsx
  components/Scoped/Settings/FSettingsFormScreen.jsx
  components/Scoped/Settings/FSettingsScreen.jsx
  components/Scoped/UserProfile/FUserProfileCard.jsx
  constants/stackNavigatorNames.js
  layouts/FDefault.layout.jsx
  layouts/FFormLayout.jsx
  layouts/FWelcome.layout.jsx
  layouts/components/FContainer.jsx
  layouts/components/FKeyboardWrapper.jsx
  navigation/Navigation.jsx
  package.json
  screens/AddAnnouncement.screen.jsx
  screens/AnnouncementPreview.screen.jsx
  screens/ChangePassword.screen.jsx
  screens/ForgotPassword.screen.jsx
  screens/Homepage.screen.jsx
  screens/LoginHistory.screen.jsx
  screens/Settings.screen.jsx
  screens/UserProfile.screen.jsx
  screens/UserProfilePreview.screen.jsx
  services/announcement/getOtherAnnouncement.service.js
  storybook/stories/Inputs/FColorSelect.stories.js
  styles/defaultBoxShadow.js
  styles/utils/getHalfBorderRadius.js
  themes/icons.js
  themes/opacities.js
  themes/sizes.js
  yarn.lock
Labels: feature

#60 FM-219 | Create announcement tile
  components/Composition/FHeading.jsx
  components/Composition/FHeadingWithIcon.jsx
  components/Inputs/FTileSelectInput.jsx
  components/Scoped/Announcement/FAnnouncementCard.jsx
  components/Utils/FPhoneNumber.jsx
  constants/locales.js
  constants/stackNavigatorNames.js
  layouts/FWelcome.layout.jsx
  navigation/Navigation.jsx
  screens/Homepage.screen.jsx
  themes/icons.js
  themes/sizes.js
Labels: dont merge, feature

#64 FM-225 | Announcement edit form
  .eslintrc.js
  components/Buttons/FButton.jsx
  components/Composition/Slider/FSlider.jsx
  components/Forms/Annoucement/FAnnouncementForm.jsx
  components/Forms/Annoucement/FCreateAnnouncementForm.jsx
  components/Forms/Annoucement/FEditAnnouncementForm.jsx
  components/Inputs/Custom/FImageSelectInput.jsx
  components/Inputs/FTileImageInput.jsx
  components/Inputs/Map/FMapView.jsx
  constants/components/buttonTypes.js
  constants/locales.js
  constants/stackNavigatorNames.js
  hooks/form/useAnnouncementForm.js
  navigation/Navigation.jsx
  screens/AddAnnouncement.screen.jsx
  screens/AnnouncementPreview.screen.jsx
  screens/EditAnnouncement.screen.jsx
  screens/Homepage.screen.jsx
  services/announcement/getAnnouncement.service.js
  services/announcement/getOtherAnnouncement.service.js
  services/announcement/updateAnnouncement.service.js
  themes/colors.js
  themes/icons.js
  themes/sizes.js
Labels: feature

#66 FM-248 | Ability to add announcement to favourites
  components/Composition/FModal.jsx
  components/Forms/Annoucement/FCreateAnnouncementForm.jsx
  components/Forms/Annoucement/FEditAnnouncementForm.jsx
  components/Forms/FLoginForm.jsx
  components/Forms/FRegistrationForm.jsx
  components/Inputs/Custom/FCategoryAnimalTileSelectInput.jsx
  components/Inputs/FTileImageInput.jsx
  components/Scoped/LoginHistory/FLoginHistoryList.jsx
  components/Scoped/Settings/FSettingsFormScreen.jsx
  constants/components/modals/modalTypes.js
  constants/components/modals/modalsMessages.js
  constants/locales.js
  constants/stackNavigatorNames.js
  hooks/permissions/useCameraPermission.js
  hooks/permissions/useCameraRollPermission.js
  hooks/permissions/useLocationPermission.js
  hooks/useErrorModal.js
  screens/AnnouncementPreview.screen.jsx
  screens/ChangePassword.screen.jsx
  screens/ForgotPassword.screen.jsx
  screens/Homepage.screen.jsx
  screens/UserProfile.screen.jsx
  services/announcement/addAnnouncementToFavourites.service.js
  services/announcement/removeAnnouncementFromFavourites.service.js
  storybook/stories/Compositional/FModal.stories.js
  themes/icons.js
Labels: feature

#67 FM-234 | Add aniamted actions modal to announcement card
  components/Forms/Annoucement/FEditAnnouncementForm.jsx
  components/Scoped/Announcement/Card/FAnnouncementCardActionsModal.jsx
  components/Scoped/Announcement/FAnnouncementCard.jsx
  screens/AnnouncementPreview.screen.jsx
  screens/Homepage.screen.jsx
  themes/sizes.js
Labels: feature

#68 FM-242 | Create single select input + select slice in redux
  components/Forms/FRegistrationForm.jsx
  components/Inputs/Select/FSelectInput.jsx
  components/Inputs/Select/FSelectOption.jsx
  components/Inputs/Select/FSelectOptions.jsx
  constants/stackNavigatorNames.js
  navigation/Navigation.jsx
  screens/Select.screen.jsx
  store/select/selectSlice.js
  store/store.js
  themes/icons.js
Labels: feature
